<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGp3gqzk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGp3gqzk/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerGp3gqzk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerGp3gqzk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerGp3gqzk\appProdProjectContainer([
    'container.build_hash' => 'Gp3gqzk',
    'container.build_id' => '91c03df7',
    'container.build_time' => 1636039340,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGp3gqzk');
