<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIzarmat\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIzarmat/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIzarmat.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIzarmat\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIzarmat\appProdProjectContainer([
    'container.build_hash' => 'Izarmat',
    'container.build_id' => 'cf183b6f',
    'container.build_time' => 1636039443,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIzarmat');
